tasks:
  - name: Install Playwright
    command: npx -y playwright install --with-deps
  - name: Dev Server
    init: npm ci
    command: npm run dev
ports:
  - name: Dev Server
    port: 1234
    onOpen: open-preview
vscode:
  extensions:
    - ms-playwright.playwright
