image:
  file: .gitpod.Dockerfile
tasks:
  - name: Dev Server
    init: npm ci
    command: |
      npx cypress install
      npm run vite
ports:
  - name: Dev Server
    port: 5173
    onOpen: open-preview
