tasks:
  - name: Dev Server
    init: npm ci
    command: |
      npx playwright install --with-deps
      npm run vite
ports:
  - name: Dev Server
    port: 5173
    onOpen: open-preview
vscode:
  extensions:
    - ms-playwright.playwright
