name: Publish to GitHub Pages
on:
  push:
    branches:
      - source
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.0
        with:
          dir: build
          branch: master
          token: ${{ secrets.ACCESS_TOKEN }}
