name: Publish to GitHub Pages
on:
  push:
    branches:
      - source
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Build
        run: |
          npx pnpm install
          npx pnpm run test
          npx pnpm run build
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: master
          force_orphan: true
