name: External Links Validator
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          fail: false
      - name: Create an issue if needed
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
